#!/usr/bin/env bash
# Build the objdiff target-file baseline for the th10 reconstruction:
#
#   1. Compile every reconstruction module to build/cpp/<Name>.obj with the
#      MSVC toolchain (scripts/compile-main-chain-cpp.sh).
#   2. Dump each object's disassembly and COFF symbol table into
#      build/ours/ (per-module .asm/.sym).
#   3. Extract the per-function reference disassembly/bytes of the original
#      binary into build/reference/ (scripts/extract_reference_functions.py).
#   4. Regenerate objdiff.yml so every reconstruction module is registered
#      as a diff unit (source -> object).
#
# The exact-match workflow then compares build/ours/<Module>.asm against
# build/reference/<address>_<name>.asm per function, using the COFF symbol
# table (MSVC-mangled names) to locate each semantic body inside its object.
set -euo pipefail
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

bash scripts/compile-main-chain-cpp.sh

mkdir -p build/ours
for obj in build/cpp/*.obj; do
    name="$(basename "$obj" .obj)"
    objdump -d -M intel "$obj" > "build/ours/${name}.asm" 2>/dev/null || true
    objdump -t "$obj" > "build/ours/${name}.sym" 2>/dev/null || true
done

python3 scripts/extract_reference_functions.py

python3 - <<'PY'
import glob
import os
import re

repo = os.getcwd()
units = []
for cpp in sorted(glob.glob("src/*.cpp")):
    name = os.path.basename(cpp)[:-4]
    obj = "build/cpp/%s.obj" % name
    if os.path.exists(obj):
        units.append((cpp, obj))

with open("objdiff.yml", "w") as f:
    f.write("# Generated by scripts/objdiff-baseline.sh — do not edit by\n"
            "# hand; re-run the script after adding modules.\n")
    f.write("min_versions: 2\n")
    f.write("units:\n")
    for cpp, obj in units:
        f.write("  - path: %s\n" % cpp)
        f.write("    target: %s\n" % obj)
print("objdiff.yml: %d units" % len(units))
PY

echo "baseline ready: build/reference/ (reference), build/ours/ (objects)"
