#include "GeneratedFontTable.hpp"

namespace th10 {

namespace {

extern GeneratedSurface g_GeneratedSurface; // TH10 DAT_00474cb0
extern u32 g_GeneratedRandomState; // TH10 DAT_004918b0, low 16 bits used
extern u32 g_GeneratedRandomCounter; // TH10 DAT_004918b4
extern GdiHandle g_GeneratedFontSlots[14]; // logical map: 0x4918a0 - 4*i

extern GdiHandle CreateGeneratedFontA(i32 height, const char *face_name);
extern void DeleteGeneratedGdiObject(GdiHandle handle);

const char kGeneratedFontFaceName[] = {
    static_cast<char>(0x82), static_cast<char>(0x6c),
    static_cast<char>(0x82), static_cast<char>(0x72), ' ',
    static_cast<char>(0x83), static_cast<char>(0x53),
    static_cast<char>(0x83), static_cast<char>(0x56),
    static_cast<char>(0x83), static_cast<char>(0x4e), 0
};

u32 AdvanceGeneratedState(u32 state)
{
    u32 value = state & 0xffff;
    value = (value ^ 0x9630U) - 0x6553U;
    value = ((value >> 14) + (value << 2)) & 0xffff;
    return value;
}

} // namespace

// TH10 0x00437a00. Surface construction retry and fonts are intentionally
// independent: failed DIB creation does not suppress generated bytes or fonts.
void InitializeGeneratedTableAndFonts()
{
    if (!ConstructGeneratedSurfaceEaxAbi(&g_GeneratedSurface, 0x400, 0x40,
                                         0x1a)) {
        ConstructGeneratedSurfaceEaxAbi(&g_GeneratedSurface, 0x400, 0x40,
                                        0x15);
    }

    u32 state = g_GeneratedRandomState;
    for (i32 index = 0; index < 0x100; ++index) {
        state = AdvanceGeneratedState(state);
        g_GeneratedSurface.generated[index] = static_cast<u8>(state >> 9);
    }
    g_GeneratedRandomState = state;
    g_GeneratedRandomCounter += 0x100;

    for (i32 index = 0; index < 14; ++index) {
        const i32 height = 0x20 + index * 2;
        g_GeneratedFontSlots[index] = CreateGeneratedFontA(
            height, kGeneratedFontFaceName);
    }
}

// TH10 0x00437d10. Slots deliberately remain unchanged after DeleteObject;
// repeated initialization/teardown has the same stale-handle behavior.
void DestroyGeneratedTableAndFonts()
{
    DestroyGeneratedSurfaceEsiAbi(&g_GeneratedSurface);
    for (i32 index = 0; index < 14; ++index)
        DeleteGeneratedGdiObject(g_GeneratedFontSlots[index]);
}

} // namespace th10
